--
-- PostgreSQL database dump
--

-- Dumped from database version 11.3
-- Dumped by pg_dump version 11.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: cases_agegroup; Type: TABLE; Schema: public; Owner: arjo
--

SET search_path TO public;
DROP TABLE IF EXISTS public.cases_agegroup CASCADE;

CREATE TABLE IF NOT EXISTS public.cases_agegroup (
 age_group text,
 total_num_case integer NOT NULL,
 total_num_intensivecare integer NOT NULL,
 total_num_death integer NOT NULL,
 PRIMARY KEY (age_group)
);

ALTER TABLE public.cases_agegroup OWNER TO arjo;


--
-- Name: vacc_region_agegroup; Type: TABLE; Schema: public; --Owner: arjo
--
/*
 one to many: Age group has many vaccinations
*/

SET search_path TO public;
DROP TABLE IF EXISTS public.vacc_region_agegroup CASCADE;

CREATE TABLE IF NOT EXISTS public.vacc_region_agegroup (
    id integer NOT NULL,
    region  text,
    kommun_namn text,
    age_group   text,
    population  integer NOT NULL,
    num_minst_1_dos    integer NOT NULL,
    num_fully_vaccinated    integer NOT NULL,
    proportion_of_minst_1_dos    float NOT NULL,
    proportion_of_fully_vaccinated    float NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (age_group)
      REFERENCES cases_agegroup(age_group) ---ON DELETE CASCADE
);


ALTER TABLE public.vacc_region_agegroup OWNER TO arjo;

--

--
-- Data for Name: cases_agegroup; Type: TABLE DATA; Schema: public; Owner: arjo
--

COPY public.cases_agegroup (age_group, total_num_case, total_num_intensivecare, total_num_death) FROM stdin (format csv, delimiter ',', header true);
0-9,34988,37,9
10-19,163093,53,5
20-29,203508,215,25
30-39,206199,368,46
40-49,210361,865,123
50-59,180902,1707,389
60-69,91334,2251,1063
70-79,42062,1959,3367
80-89,25541,436,6093
>=90,11394,10,3896
Uppgift-saknas,148,1,0
\.

---

--
-- Data for Name: vacc_region_agegroup; Type: TABLE DATA; Schema: public; Owner: arjo
--
\COPY vacc_region_agegroup(id,region,kommun_namn,age_group,population,num_minst_1_dos,num_fully_vaccinated,proportion_of_minst_1_dos,proportion_of_fully_vaccinated) FROM '/Users/arjo/desktop/fwd/covid_se/database/Folkhalsomyndigheten_Covid19_vaccination_summary_modified.csv' DELIMITER ',' CSV HEADER;


--
-- PostgreSQL database dump complete
--
